# Generated by Django 3.2.20 on 2025-05-22 05:27

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import rainwater_harvester.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_data', djongo.models.fields.EmbeddedField(model_container=rainwater_harvester.api.models.UserInput, null=True)),
                ('data', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'calculation_results',
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'historical_data',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user_inputs',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('data', djongo.models.fields.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
